### ISSUE TITLE
Connector/J version 8.0.13 connetion issue

### ISSUE THREAD

**Issue by afattahi54** [msdousti/OWASP-Java#1]
With:

- mysql-connector-java-8.0.18
- MySql Server:  8.0.18
- Payara 5.193

I got below error:

````
The last packet sent successfully to the server was ? milliseconds ago. 
The driver has not received any packets from the server.

````

As a workaround I set `sslMode `to `DISABLED`. 

Any suggestion ?! 

Thanks for your comment at: https://github.com/payara/Payara/issues/2747#issuecomment-552618627 !

**Comment by msdousti** [comment]
I updated the readme file of the project, which states that `sslMode` must be set to `DISABLED`.  This makes the issue go away.

If one wants SSL connection between Payara and MySQL, `clientCertificateKeyStoreUrl` and `clientCertificateKeyStorePassword` must be configured properly. Furthermore, MySQL's CA certificate must be added to Payara's truststore.
